#User register
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Andres",
    "email": "email2@gmail.com",
    "password": "123456"
}

###

#User login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "email2@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3000/solve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc0MjRlZDYzLTRhMTYtNDhlNS1iZGI0LWQ5YjNiZjgxMGVkMCIsImlhdCI6MTc2NjE2OTU0OSwiZXhwIjoxNzY2MTczMTQ5fQ.2-Yuwd568jz315mslhlhPfcLdNqm0y9m1zAbrn9voaQ

{
  "time": 15342,
  "scramble": "R U R' U' F2 D"
}