#User register
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Andres",
    "email": "email3@gmail.com",
    "password": "123456"
}

###

#User login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "email3@gmail.com",
  "password": "123456"
}

###
# Add a solve to db
POST http://localhost:3000/solve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU3NjA0NTY4LTNkYmUtNDM4OC1hM2EwLTlhMDBiZjZmMDQzZCIsImlhdCI6MTc2NjIwMzQ0MCwiZXhwIjoxNzY2MjA3MDQwfQ.hk-AZf0tfud873Px-Ntyo5IinYsIVpYIh8Z6WIJ8mjo

{
  "time": 15342,
  "scramble": "R U R' U' F2 D U L'"
}

###
# GET user profile

GET http://localhost:3000/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU3NjA0NTY4LTNkYmUtNDM4OC1hM2EwLTlhMDBiZjZmMDQzZCIsImlhdCI6MTc2NjIwMzQ0MCwiZXhwIjoxNzY2MjA3MDQwfQ.hk-AZf0tfud873Px-Ntyo5IinYsIVpYIh8Z6WIJ8mjo

###
#GET user times

GET http://localhost:3000/profile/times
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU3NjA0NTY4LTNkYmUtNDM4OC1hM2EwLTlhMDBiZjZmMDQzZCIsImlhdCI6MTc2NjIwMzQ0MCwiZXhwIjoxNzY2MjA3MDQwfQ.hk-AZf0tfud873Px-Ntyo5IinYsIVpYIh8Z6WIJ8mjo